BlazejStachura/urls.py
from django.contrib import admin
from django.urls import path, include

from www.views import OfferPage, MainPage, BlogPage, ContactPage, \
    CalendarView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view(), name='Main'),
    path('oferta/', OfferPage.as_view(), name='Offer'),
    path("kalendarz/", CalendarView.as_view(), name="calendar"),
    path('blog/', include("blog.urls",namespace='blog')),
    path('kontakt/', ContactPage.as_view(), name='Contact'),
]

blog/urls.py
from django.urls import path

from blog import views
from blog.views import *

app_name = "blog"

urlpatterns = [
    path("", post_list, name='post_list'),
    # path("<int:year>/<int:month>/<int:day>/<slug:post>/",
    #      post_detail.as_view(),
    #      name='post_detail'),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/",
         PostListView.as_view(),
         name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share')
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset() \
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = {
        ('draft', 'Draft'),
        ('published', 'Published')
    }
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    def __str__(self):
        return f'Komentarz dodany przez {self.name} dla posta {self.post}.'

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views import View
from django.views.generic import ListView

from blog.models import Post
from www.forms import EmailPostForm


def post_list(request):
    posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'posts': posts})


# def post_detail(request, year, month, day, post):
#     post = get_object_or_404(Post, slug=post,
#                              status='published',
#                              publish__year=year,
#                              publish__month=month,
#                              publish__date=day)
#     return render(request, 'blog/detail.html', {'post': post})


# class post_detail(View):
#     def get(self, request, year, month, day, post):
#         post = get_object_or_404(Post, slug=post,
#                                  status='published',
#                                  publish__year=year,
#                                  publish__month=month,
#                                  publish__date=day)
#         return render(request, 'blog/detail.html', {'post': post})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    # pobieranie posta na podstawie jego identyfikatora
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} {{}} zachęca do przeczytania "{}"'.format(cd['name'], cd['email'], post.title)
            message = f'Przeczytaj post "{post.title}" na stronie {post_url}' \
                      f'\n\n Komentarz dodany przez {cd["name"]} : {cd["email"]}'
            EMAIL_HOST = 'smtp.gmail.com'
            EMAIL_HOST_USER = 'twoja_nazwa_konta_uzytkownika'
            EMAIL_HOST_PASSWORD = 'twoje haslo'
            EMAIL_PORT = 587
            EMAIL_USE_TLS = True
            print(cd)
            send_mail(subject, message, 'mateuszczaja086@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent
                                                    })

templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}
    <p><a href="{% url "blog:post_share" post.id %}">{{ post.title }}</a></p>
    <h2>sdsadasdsaddsa</h2>
  {{ post.body|linebreaks }}
{% endblock %}

templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mój Blog{% endblock %}

{% block content %}
  <h1>Mój blog</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Udostępnij post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>Wiadomość email została wysłana</h1>
        <p>Wysyłanie posta "{{ post.title }}" do {{ form.cleaned_data.to }} zakończyło się sukcesem.</p>
        {% else %}
        <h1>Udostępnij "{{ post.title }}" przez email.</h1>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}>
        <input type="submit" value="Wyślij wiadomość email.">
        </form>
    {% endif %}
{% endblock content %}